name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci
        
      - name: Create env file
        run: |
          touch .env
          echo TOKEN_SECRET=$TOKEN_SECRET>> .env
          echo SALT=$SALT >> .env
          echo DB_PASS=$DB_PASS >> .env
          echo DB_USER=$DB_USER >> .env
          cat .env
        
      - name: Restart server application
        run: pm2 restart api
